'use client';

import { useRouter } from 'next/navigation';

export default function UsagePolicyPage() {
  const router = useRouter();
  return (
    <div className="min-h-screen bg-background text-primary">
      <div className="sticky top-0 z-10 bg-background/95 backdrop-blur border-b border-default px-6 py-4 flex items-center justify-between">
        <button onClick={() => router.back()} className="text-secondary text-sm hover:text-primary transition-colors">← Back</button>
        <span className="text-xs text-muted uppercase tracking-widest">Usage Policy</span>
        <div className="w-10" />
      </div>
      <div className="max-w-2xl mx-auto px-6 py-16 space-y-10">
        <div>
          <div className="text-xs text-purple-400 uppercase tracking-widest mb-3">Legal</div>
          <h1 className="text-3xl font-bold text-primary mb-2" style={{fontFamily:'var(--font-playfair)'}}>Usage Policy</h1>
          <p className="text-muted text-sm">Last updated: March 2026 · artNXT Company, Stuttgart, Germany</p>
        </div>

        {[
          {
            title: 'What StudioNXT Is For',
            content: 'StudioNXT is a professional digital archive for individual artists. It is designed for documenting original artworks, tracking editions and locations, recording the artist\'s voice and intentions, generating professional documents, and designating a legacy contact.'
          },
          {
            title: 'What You Can Do',
            content: 'Upload photographs of your original artworks. Create catalogue records. Track editions and physical locations. Record voice sessions. Upload supporting documents (contracts, certificates, press, catalogues). Generate AI-assisted statements and biographies. Export your data at any time.'
          },
          {
            title: 'What You Cannot Do',
            content: 'You may not upload images of artworks you do not own or have rights to document. You may not create false edition records or misrepresent provenance. You may not share your account with other artists. You may not use StudioNXT to document stolen artworks. You may not attempt to access another user\'s archive.'
          },
          {
            title: 'Artwork Records',
            content: 'StudioNXT is designed to be a truthful record. Edition sizes cannot be increased after declaration. Creating false records may have legal implications for provenance and sale. We are not responsible for the legal consequences of false records created by users.'
          },
          {
            title: 'AI-Generated Content',
            content: 'Content generated by Mira (Claude) and the bio generator (Gemini) is a starting point — not a final statement. The artist is responsible for reviewing and approving all AI-generated content before use. We do not use your artwork data to train AI models.'
          },
          {
            title: 'The Legacy System',
            content: 'The legacy contact feature is a convenience tool. It does not constitute a legal will, grant legal rights to the designated contact, or override the laws of any jurisdiction regarding estates. Please consult a lawyer for formal estate planning.'
          },
          {
            title: 'Enforcement',
            content: 'Violations may result in a warning, temporary suspension, permanent account termination, or referral to relevant authorities where required by law.'
          },
        ].map(s => (
          <div key={s.title} className="border-b border-default pb-8">
            <h2 className="text-lg font-semibold text-primary mb-3" style={{fontFamily:'var(--font-playfair)'}}>{s.title}</h2>
            <p className="text-secondary leading-relaxed text-sm">{s.content}</p>
          </div>
        ))}

        <p className="text-muted text-xs">This document is a draft pending legal review. · Dieses Dokument ist ein Entwurf.</p>
      </div>
    </div>
  );
}
